-- Code generated by schema merge script. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS jwt (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL references users(id),
    expiration_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_available bool NOT NULL DEFAULT true
    );CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );CREATE TABLE IF NOT EXISTS forms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT,
    author_id TEXT references users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );CREATE TABLE IF NOT EXISTS bookmarks
(
    form_id UUID REFERENCES forms (id),
    user_id UUID REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (form_id, user_id)
)