// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package jwt

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO jwt (user_id, expiration_time)
VALUES ($1, $2)
RETURNING id, user_id, expiration_time, is_available
`

type CreateParams struct {
	UserID         uuid.UUID
	ExpirationTime pgtype.Timestamptz
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Jwt, error) {
	row := q.db.QueryRow(ctx, create, arg.UserID, arg.ExpirationTime)
	var i Jwt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
	)
	return i, err
}

const isAvailable = `-- name: IsAvailable :one
SELECT id, user_id, expiration_time, is_available FROM jwt
where id = $1
limit 1
`

func (q *Queries) IsAvailable(ctx context.Context, id uuid.UUID) (Jwt, error) {
	row := q.db.QueryRow(ctx, isAvailable, id)
	var i Jwt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE jwt SET is_available = $2
where id = $1
RETURNING id, user_id, expiration_time, is_available
`

type UpdateParams struct {
	ID          uuid.UUID
	IsAvailable bool
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Jwt, error) {
	row := q.db.QueryRow(ctx, update, arg.ID, arg.IsAvailable)
	var i Jwt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpirationTime,
		&i.IsAvailable,
	)
	return i, err
}
