// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package form

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO forms (title, description, author_id)
VALUES ($1, $2, $3)
RETURNING id, title, description, author_id, created_at
`

type CreateParams struct {
	Title       string
	Description pgtype.Text
	AuthorID    pgtype.Text
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Form, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.Description, arg.AuthorID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM forms WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const isBookmarked = `-- name: IsBookmarked :one
SELECT EXISTS(
    SELECT 1 FROM bookmarks
    where form_id = $1 and user_id = $2
)
`

type IsBookmarkedParams struct {
	FormID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsBookmarked(ctx context.Context, arg IsBookmarkedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBookmarked, arg.FormID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const list = `-- name: List :many
SELECT id, title, description, author_id, created_at FROM forms
ORDER BY id
`

func (q *Queries) List(ctx context.Context) ([]Form, error) {
	rows, err := q.db.Query(ctx, list)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE forms SET title = $2, description = $3
where id = $1
RETURNING id, title, description, author_id, created_at
`

type UpdateParams struct {
	ID          uuid.UUID
	Title       string
	Description pgtype.Text
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Form, error) {
	row := q.db.QueryRow(ctx, update, arg.ID, arg.Title, arg.Description)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}
