// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	form "awesomeProject/internal/form"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, name, description, authorId
func (_m *Store) Create(ctx context.Context, name string, description string, authorId uuid.UUID) (form.Form, error) {
	ret := _m.Called(ctx, name, description, authorId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 form.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) (form.Form, error)); ok {
		return rf(ctx, name, description, authorId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uuid.UUID) form.Form); ok {
		r0 = rf(ctx, name, description, authorId)
	} else {
		r0 = ret.Get(0).(form.Form)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, uuid.UUID) error); ok {
		r1 = rf(ctx, name, description, authorId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Store) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsBookmarked provides a mock function with given fields: ctx, formId, userId
func (_m *Store) IsBookmarked(ctx context.Context, formId uuid.UUID, userId uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, formId, userId)

	if len(ret) == 0 {
		panic("no return value specified for IsBookmarked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, formId, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, formId, userId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, formId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *Store) List(ctx context.Context) ([]form.Form, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []form.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]form.Form, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []form.Form); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]form.Form)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, name, description
func (_m *Store) Update(ctx context.Context, id uuid.UUID, name string, description string) (form.Form, error) {
	ret := _m.Called(ctx, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 form.Form
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (form.Form, error)); ok {
		return rf(ctx, id, name, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) form.Form); ok {
		r0 = rf(ctx, id, name, description)
	} else {
		r0 = ret.Get(0).(form.Form)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = rf(ctx, id, name, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
