#!/usr/bin/env bash

# This script merges all schema.sql files found in the internal directory and subdirectories into a single SQL file.
# It is used to create a full schema file for sqlc.

set -e

# Default values
OUTPUT_FILE="./internal/database/full_schema.sql"
SQLC_YAML="./sqlc.yaml"

# Print help message
print_help() {
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo "  --output-file PATH     Path to the merged schema output file (default: ./internal/database/full_schema.sql)"
    echo "  --sqlc-yaml PATH       Path to the generated sqlc.yaml file (default: ./sqlc.yaml)"
    echo "  --help                 Show this help message and exit"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --output-file)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --sqlc-yaml)
            SQLC_YAML="$2"
            shift 2
            ;;
        --help)
            print_help
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            print_help
            exit 1
            ;;
    esac
done

SCHEMA_FILES=()

# Automatically find all schema.sql files under internal directory
mapfile -t SCHEMA_FILES < <(find ./internal -type f -name "schema.sql")

# Clear and initialize the schema file
echo -e "-- Code generated by schema merge script. DO NOT EDIT.\n" > "$OUTPUT_FILE"

# Merge schema files
for SCHEMA in "${SCHEMA_FILES[@]}"; do
    cat "$SCHEMA" >> "$OUTPUT_FILE"
done

# Start generating sqlc.yaml
cat > "$SQLC_YAML" << 'EOF'
# Code generated by schema merge script. DO NOT EDIT.
version: "2"
sql:
EOF

# Find all directories containing queries.sql and generate config
find ./internal -type f -name "queries.sql" | while read -r QUERY_FILE; do
    PACKAGE_DIR=$(dirname "$QUERY_FILE")
    PACKAGE_NAME=$(basename "$PACKAGE_DIR")

    cat >> "$SQLC_YAML" << EOF
  - engine: "postgresql"
    queries: "$QUERY_FILE"
    schema: "$OUTPUT_FILE"
    gen:
      go:
        package: "$PACKAGE_NAME"
        out: "$PACKAGE_DIR"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
EOF
done