// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO users (email)
VALUES ($1)
RETURNING id, email, created_at
`

func (q *Queries) Create(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, create, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT  EXISTS(SELECT 1 FROM users WHERE email = $1) AS exists
`

func (q *Queries) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, created_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT id, email, created_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
